"""create table category product

Revision ID: aecf6d15bd99
Revises: 188d5861aece
Create Date: 2024-12-05 15:37:29.253905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aecf6d15bd99'
down_revision = '188d5861aece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_product',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=140), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_product')
    # ### end Alembic commands ###
